theme: jekyll-theme-hydure

plugins:
  - jekyll-remote-theme

collections:
  robots:
    output: true
      #permalink: /Projects/Robots/:name/
  honeylyrics:
    output: true
    #permalink: /Projects/HoneyLyrics/:name/
  algorithm:
    collections_dir: /study/alogrithm
    output: true
    permalink: /study/algorithm/:name/


remote_theme: zivong/jekyll-theme-hydure

title: soohyun

author.name: soohyun
author.url: kimSooHyun950921.github.io

# Ruby Date Format
date_format: "%B %-d, %Y"

# permalink: /:year-:month-:day-:title/

permalink: /:categories/:title/
comments: true
description: "내공내블 - 내가공부하려고 만든 블로그"
