theme: jekyll-theme-hydure

plugins:
  - jekyll-remote-theme

collections:
  Projects:
    Robots:
      output: true
      permalink: /Projects/Robots/:name/
    HoneyLyrics:
      output: true
      permalink: /Projects/HoneyLyrics/:name/
  Study:
     AI:
      output: true
      permalink: /Study/AI/:name/

#defaults:
#  - scope:
#      path: ""
#      type: "Projects"
#    values:
#      layout: "post"
#  - scope:
#      path: ""
#      type: "Study"
#   values:
#      layout: "post"

remote_theme: zivong/jekyll-theme-hydure

title: soohyun

author.name: soohyun
author.url: kimSooHyun950921.github.io

# Ruby Date Format
date_format: "%B %-d, %Y"

# permalink: /:year-:month-:day-:title/

permalink: /:categories/:title/
comments: true
description: "내공내블 - 내가공부하려고 만든 블로그"
